name: Bug Report 错误报告
description: Report bugs 报告错误
labels: bug
body:
- type: input
  attributes:
    label: Version 程序版本
  validations:
    required: true
- type: textarea
  attributes:
    label: bug's screenshot 错误截图
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduction steps 复现步骤
    description: >
      Describe the reproduction steps precisely if possible. 
      
      尽可能详细描述错误产生的细节。
  validations:
    required: true