name: Release

on:
  workflow_dispatch: # allows manual triggering
    inputs:
      create_release:
        description: 'Create new release'
        required: true
        type: string
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      # 矩阵配置
      matrix:
        include:
          - architecture: x86
            fname: LunaTranslator_x86
          - architecture: x64
            fname: LunaTranslator
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Windows 10 SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22621
      - name: Install Python 3.7.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.7.9'
          architecture: ${{ matrix.architecture }}
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: x64
      - name: Install Python 3.11 req
        run: pip install cmake pefile requests
      - name: Run build script
        run: |
          python build.py ${{ matrix.architecture }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fname }}
          path: build/${{ matrix.fname }}.zip

      - name: Release LunaTranslator
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.create_release }}
          files: build/${{ matrix.fname }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
